# Generated by Django 3.1.7 on 2021-02-25 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_CO2', models.FloatField()),
                ('minute_heat_rate_avg', models.FloatField()),
                ('plant_efficiency', models.FloatField()),
                ('co2_reserve', models.PositiveBigIntegerField()),
                ('measured_date', models.DateField(default=datetime.date(2021, 2, 25))),
                ('measured_at_minute', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
